"""signed col

Revision ID: 2602645f8eb8
Revises: 290127e82ebe
Create Date: 2024-11-23 11:42:27.052832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2602645f8eb8'
down_revision: Union[str, None] = '290127e82ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('signed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'signed_date')
    # ### end Alembic commands ###
